Mobile version
BouaikIlham/Portfolio-project pull request #2
Opened 2022-03-22 21:00 UTC by BouaikIlham

- [ ] add linter
- [ ] used correct [GitHub Flow](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/git-github/articles/github_flow.md):
- [ ] README file
- [ ] Pull Request is made from 'feature branch' into the main branch.
- [ ] add "Works" section
- [ ] add the "About myself" section

2022-03-22 22:42 UTC, akucintavalent requested changes
Hi there, @BouaikIlham 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

### To highlight :tada: :champagne: 
- Nice README file :heavy_check_mark:
- GitHub flow is followed :+1:


## Required Changes ♻️
- [ ] Please always try to preserve the distance between elements like the template does.
<img width="150" alt="Zrzut ekranu 2022-03-22 o 23 41 42" src="https://user-images.githubusercontent.com/87897753/159588366-8f48d4a4-4e5f-48ab-8d22-6f97e15cf26a.png">

- [ ] Kindly do your best to follow the Figma design as much as possible.
- [ ] Kindly checkout Chrome Dev Tools and try to check how your page looks on different mobile devices. Try to always check how your page looks on different mobile devices and try to make it as responsive as possible.
- [ ] [OPTIONAL] In your README file, please replace `cd Hello-Microverse` with `cd Portfolio-project`. Please provide information on what exactly the user has to open and how. The phrase "using live server" could be not understandable to some people. 
<img width="746" alt="image" src="https://user-images.githubusercontent.com/87897753/159578679-42ba8709-20ff-46a7-99b5-15c344742282.png">
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-03-22 22:42 UTC, akucintavalent commented on index.html
> +          <button type="button" class="see-btn">See Project</button>
Please wrap each project card into its own container. We will need all card elements to be grouped into separate cards later on. You should apply `display: flexbox` to each project card. Kindly wrap all cards (`div` elements that represent cards) into one container and use `display: grid` CSS property to align the cards.

2022-03-22 22:42 UTC, akucintavalent commented on index.html
> +          <button type="button" class="see-btn">See Project</button>
Your buttons should have different styles applied when in a normal state, when you hover over them, and when they are pressed. Kindly follow the Figma template.

<img width="331" alt="image" src="https://user-images.githubusercontent.com/87897753/159582804-7e4db62b-4ace-4bcc-a7cb-08c1c332bd1e.png">

2022-03-22 22:42 UTC, akucintavalent commented on index.html
> +      </li>
Kindly use the proper fonts  in this section like in the template:

<img width="337" alt="image" src="https://user-images.githubusercontent.com/87897753/159583786-53ac2d56-1123-40a5-b855-8db0e8a1443c.png">

<img width="416" alt="image" src="https://user-images.githubusercontent.com/87897753/159583894-7184cc9e-5696-46cc-aae1-fddf6d1ce1fb.png">

2022-03-22 22:42 UTC, akucintavalent commented on index.html
> +    </ul>
The technology categories ("Languages", "Frameworks" and "Skills") should in one `ul`, each of them in a `li`

2022-03-22 22:42 UTC, akucintavalent commented on index.html
> +  <section class="about-me">
Please align the content of the section with flexbox.

2022-03-22 22:42 UTC, akucintavalent commented on index.html
>    <section class="section">
The background of the greeting sections should be write according to the Figma template.

Yours:
<img width="375" alt="image" src="https://user-images.githubusercontent.com/87897753/159585857-48c49cbc-7659-46d9-b1ff-4498f9bba59a.png">

Figma's
<img width="247" alt="image" src="https://user-images.githubusercontent.com/87897753/159585936-ce4985d4-c2b0-462c-a0f1-c044193bcaa7.png">

2022-03-22 22:42 UTC, akucintavalent commented on index.html
> +          <button type="button" class="see-btn">See Project</button>
Each card should have white background:

Yours:
<img width="364" alt="image" src="https://user-images.githubusercontent.com/87897753/159586393-d651ad91-a566-4415-a2d9-069ff3bd9ade.png">

Figma's:
<img width="230" alt="image" src="https://user-images.githubusercontent.com/87897753/159586410-c3efb04f-93bc-478a-b81b-0845f2742072.png">

2022-03-22 22:42 UTC, akucintavalent commented on index.html
> +  <section class="about-me">
About me section should have white background. And the space between My works section and About me section should look like this:

<img width="282" alt="image" src="https://user-images.githubusercontent.com/87897753/159586673-d89b19a0-489e-4660-80a2-c9fbe3a4b56a.png">

2022-03-22 22:42 UTC, akucintavalent commented on index.html
> +      </li>
The technologies categories should look like this:

<img width="215" alt="image" src="https://user-images.githubusercontent.com/87897753/159586886-77ca7eff-12dd-46bf-b121-37fafcd1731f.png">


Your design: 

<img width="336" alt="image" src="https://user-images.githubusercontent.com/87897753/159586919-9ace335f-b768-4c79-81b9-84d565e15582.png">

2022-03-23 11:06 UTC, AnselemOdims requested changes
### Hi @BouaikIlham , 
Good job implementing some of the changes requested by the previous reviewer but you still have a bit to go.

## Required Changes ♻️
- [ ] Please also check inline comments under the review

## Optional suggestions
_Comments with the [OPTIONAL] prefix are not a must to implement however, It's strongly recommended to work on them as they can make your code better._

## Happy coding!👏👏👏

#### Please leave any questions or comments in the PR if you have any doubts or unclarity! You can tag me using @AnselemOdims for a quicker response

**_Note: Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2022-03-23 11:06 UTC, AnselemOdims commented on index.html
> +          <button type="button" class="see-btn">See Project</button>
- [x] Please kindly implement this requested change

2022-03-23 11:06 UTC, AnselemOdims commented on index.html
> +          <div class="list-conatiner">
- [ ] As already stated by the previous reviewer, please ensure there is enough spacing between the headline section and the works section

### Your Design 
![image](https://user-images.githubusercontent.com/43995830/159684213-e07d5761-a3b9-4f27-9a6d-1e28c1556799.png)

### Original Design
![image](https://user-images.githubusercontent.com/43995830/159684743-25bcf62d-7119-4e4f-b30e-d301fa876fe8.png)

2022-03-23 11:46 UTC, BouaikIlham commented
@AnselemOdims I don't understand this:
 Please kindly implement this requested change 
Can you explain clearly, please?

2022-03-23 16:38 UTC, t-yanick approved these changes
Hi @BouaikIlham, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit:  
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-03-23 16:40 UTC, merged